---
apiVersion: getambassador.io/v2
kind: AuthService
metadata:
  name: authentication
spec:
  auth_service: "https://keycloak.172.27.244.246.nip.io/auth/realm/k8s/protocol/openid-connect/token"
  path_prefix: "/auth"
  allowed_request_headers:
  - "x-qotm-session"
  allowed_authorization_headers:
  - "x-qotm-session"